services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Danilovl\EntityDataListConsoleBundle\:
    resource: '../../../src'
    exclude:
      - '../../../src/DependencyInjection'
      - '../../../src/Resources'
